name: Cypress Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering of the workflow

# Add permissions needed for GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # Don't fail fast to get results from all browsers
      matrix:
        browser: [chrome, firefox]  # Run tests in both Chrome and Firefox

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Start server in background
        run: npm start & npx wait-on http://localhost:3000 --timeout 60000

      - name: Create necessary directories
        run: |
          mkdir -p cypress/reports/mochawesome
          mkdir -p cypress/screenshots
          mkdir -p cypress/videos

      - name: Run Cypress tests
        run: npm run cy:run:${{ matrix.browser }}
        env:
          CYPRESS_REPORTER: cypress-mochawesome-reporter
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Mochawesome report
        if: always()  # Run even if tests fail
        run: |
          npm run report:clean
          mkdir -p cypress/reports/mochawesome
          mkdir -p cypress/reports/html
          # Only try to merge if files exist
          if [ "$(find cypress/reports/mochawesome -name '*.json' | wc -l)" -gt 0 ]; then
            npm run report:merge
            npm run report:generate
          else
            echo "No report files found to merge. Creating empty report."
            echo '{}' > cypress/reports/mochawesome-merged.json
            npm run report:generate || echo "Failed to generate report from empty JSON"
          fi

      - name: Upload test results
        if: always()  # Run even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: cypress-report-${{ matrix.browser }}
          path: |
            cypress/reports
            cypress/screenshots
            cypress/videos
          retention-days: 30
          if-no-files-found: warn  # Don't fail if no files are found

  publish-report:
    needs: cypress-run
    if: always()  
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Merge reports from different browsers
        run: |
          mkdir -p cypress/reports/mochawesome
          mkdir -p cypress/reports/html
          # Try to copy any existing reports
          cp -r artifacts/cypress-report-*/cypress/reports/mochawesome/* cypress/reports/mochawesome/ || true
          npm install
          # Only try to merge if files exist
          if [ "$(find cypress/reports/mochawesome -name '*.json' | wc -l)" -gt 0 ]; then
            npm run report:merge
            npm run report:generate
          else
            echo "No report files found to merge. Creating empty report."
            echo '{}' > cypress/reports/mochawesome-merged.json
            npm run report:generate || echo "Failed to generate report from empty JSON"
          fi

      - name: Check if reports exist
        id: check_reports
        run: |
          if [ -d "./cypress/reports/html" ] && [ "$(find ./cypress/reports/html -type f | wc -l)" -gt 0 ]; then
            echo "reports_exist=true" >> $GITHUB_OUTPUT
          else
            echo "reports_exist=false" >> $GITHUB_OUTPUT
            echo "No reports found to deploy to GitHub Pages"
          fi

      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') && steps.check_reports.outputs.reports_exist == 'true'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cypress/reports/html
          destination_dir: reports/${{ github.run_number }}
          keep_files: true

      - name: Upload combined report
        uses: actions/upload-artifact@v4
        with:
          name: combined-report
          path: cypress/reports/html
          retention-days: 30
          if-no-files-found: warn  # Don't fail if no files are found
